# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ex02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex02
  pod 'ForecastIO'
  pod 'RecastAI'

  target 'ex02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ex02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
