#include "ft_printf.h"
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

void	passed_tests(void)
{
	int i, j;
	printf("\t\t\tBASIC TEST\n");
	printf("~~~~~~~~~d tests:\n");
	printf("(printf)%d %d\n", 0, 42);
	ft_printf("(ft_pri)%d %d\n", 0, 42);
	printf("(printf)%ld %ld\n", 0, 42);
	ft_printf("(ft_pri)%ld %ld\n", 0, 42);
	printf("(printf)%lld %lld\n", 0, 42);
	ft_printf("(ft_pri)%lld %lld\n", 0, 42);
	printf("(printf)%hd %hd\n", 0, 42);
	ft_printf("(ft_pri)%hd %hd\n", 0, 42);
	printf("(printf)%hhd %hhd\n", 0, 42);
	ft_printf("(ft_pri)%hhd %hhd\n", 0, 42);
	printf("(printf)%d %d\n", INT_MIN, INT_MAX);
	ft_printf("(ft_pri)%d %d\n", INT_MIN, INT_MAX);
	printf("(printf)%ld %ld\n", LONG_MIN, LONG_MAX);
	ft_printf("(ft_pri)%ld %ld\n", LONG_MIN, LONG_MAX);
	printf("(printf)%lld %lld\n", LLONG_MIN, LLONG_MAX);
	ft_printf("(ft_pri)%lld %lld\n", LLONG_MIN, LLONG_MAX);
	printf("(printf)%hd %hd\n", SHRT_MIN, SHRT_MAX);
	ft_printf("(ft_pri)%hd %hd\n", SHRT_MIN, SHRT_MAX);
	printf("(printf)%hhd %hhd\n", CHAR_MIN, CHAR_MAX);
	ft_printf("(ft_pri)%hhd %hhd\n", CHAR_MIN, CHAR_MAX);

	printf("~~~~~~~~~i tests:\n");
	printf("(printf)%i %i\n", 0, 42);
	ft_printf("(ft_pri)%i %i\n", 0, 42);
	printf("(printf)%li %li\n", 0, 42);
	ft_printf("(ft_pri)%li %li\n", 0, 42);
	printf("(printf)%lli% lli\n", 0, 42);
	ft_printf("(ft_pri)%lli %lli\n", 0, 42);
	printf("(printf)%hi %hi\n", 0, 42);
	ft_printf("(ft_pri)%hi %hi\n", 0, 42);
	printf("(printf)%hhi %hhi\n", 0, 42);
	ft_printf("(ft_pri)%hhi %hhi\n", 0, 42);	
	printf("(printf)%i %i\n", INT_MIN, INT_MAX);
	ft_printf("(ft_pri)%i %i\n", INT_MIN, INT_MAX);
	printf("(printf)%li %li\n", LONG_MIN, LONG_MAX);
	ft_printf("(ft_pri)%li %li\n", LONG_MIN, LONG_MAX);
	printf("(printf)%lli %lli\n", LLONG_MIN, LLONG_MAX);
	ft_printf("(ft_pri)%lli %lli\n", LLONG_MIN, LLONG_MAX);
	printf("(printf)%hi %hi\n", SHRT_MIN, SHRT_MAX);
	ft_printf("(ft_pri)%hi %hi\n", SHRT_MIN, SHRT_MAX);
	printf("(printf)%hhi %hhi\n", CHAR_MIN, CHAR_MAX);
	ft_printf("(ft_pri)%hhi %hhi\n", CHAR_MIN, CHAR_MAX);

	printf("~~~~~~~~~o tests:\n");
	printf("(printf)%o %o\n", 0, 42);
	ft_printf("(ft_pri)%o %o\n", 0, 42);
	printf("(printf)%lo %lo\n", 0, 42);
	ft_printf("(ft_pri)%lo %lo\n", 0, 42);
	printf("(printf)%llo %llo\n", 0, 42);
	ft_printf("(ft_pri)%llo %llo\n", 0, 42);
	printf("(printf)%ho %ho\n", 0, 42);
	ft_printf("(ft_pri)%ho %ho\n", 0, 42);
	printf("(printf)%hho %hho\n", 0, 42);
	ft_printf("(ft_pri)%hho %hho\n", 0, 42);	
	printf("(printf)%o\n", UINT_MAX);
	ft_printf("(ft_pri)%o\n", UINT_MAX);
	printf("(printf)%lo\n", ULONG_MAX);
	ft_printf("(ft_pri)%lo\n", ULONG_MAX);
	printf("(printf)%llo\n", ULLONG_MAX);
	ft_printf("(ft_pri)%llo\n", ULLONG_MAX);
	printf("(printf)%ho\n", USHRT_MAX);
	ft_printf("(ft_pri)%ho\n", USHRT_MAX);
	printf("(printf)%hho\n", UCHAR_MAX);
	ft_printf("(ft_pri)%hho\n", UCHAR_MAX);

	printf("~~~~~~~~~x tests:\n");
	printf("(printf)%x %x\n", 0, 42);
	ft_printf("(ft_pri)%x %x\n", 0, 42);
	printf("(printf)%lx %lx\n", 0, 42);
	ft_printf("(ft_pri)%lx %lx\n", 0, 42);
	printf("(printf)%llx %llx\n", 0, 42);
	ft_printf("(ft_pri)%llx %llx\n", 0, 42);
	printf("(printf)%hx %hx\n", 0, 42);
	ft_printf("(ft_pri)%hx %hx\n", 0, 42);
	printf("(printf)%hhx %hhx\n", 0, 42);
	ft_printf("(ft_pri)%hhx %hhx\n", 0, 42);	
	printf("(printf)%x\n", UINT_MAX);
	ft_printf("(ft_pri)%x\n", UINT_MAX);
	printf("(printf)%lx\n", ULONG_MAX);
	ft_printf("(ft_pri)%lx\n", ULONG_MAX);
	printf("(printf)%llx\n", ULLONG_MAX);
	ft_printf("(ft_pri)%llx\n", ULLONG_MAX);
	printf("(printf)%hx\n", USHRT_MAX);
	ft_printf("(ft_pri)%hx\n", USHRT_MAX);
	printf("(printf)%hhx\n", UCHAR_MAX);
	ft_printf("(ft_pri)%hhx\n", UCHAR_MAX);

	printf("~~~~~~~~~X tests:\n");
	printf("(printf)%X %X\n", 0, 42);
	ft_printf("(ft_pri)%X %X\n", 0, 42);
	printf("(printf)%lX %lX\n", 0, 42);
	ft_printf("(ft_pri)%lX %lX\n", 0, 42);
	printf("(printf)%llX %llX\n", 0, 42);
	ft_printf("(ft_pri)%llX %llX\n", 0, 42);
	printf("(printf)%hX %hX\n", 0, 42);
	ft_printf("(ft_pri)%hX %hX\n", 0, 42);
	printf("(printf)%hhX %hhX\n", 0, 42);
	ft_printf("(ft_pri)%hhX %hhX\n", 0, 42);	
	printf("(printf)%X\n", UINT_MAX);
	ft_printf("(ft_pri)%X\n", UINT_MAX);
	printf("(printf)%lX\n", ULONG_MAX);
	ft_printf("(ft_pri)%lX\n", ULONG_MAX);
	printf("(printf)%llX\n", ULLONG_MAX);
	ft_printf("(ft_pri)%llX\n", ULLONG_MAX);
	printf("(printf)%hX\n", USHRT_MAX);
	ft_printf("(ft_pri)%hX\n", USHRT_MAX);
	printf("(printf)%hhX\n", UCHAR_MAX);
	ft_printf("(ft_pri)%hhX\n", UCHAR_MAX);

	printf("~~~~~~~~~u tests:\n");
	printf("(printf)%u %u\n", 0, 42);
	ft_printf("(ft_pri)%u %u\n", 0, 42);
	printf("(printf)%lu %lu\n", 0, 42);
	ft_printf("(ft_pri)%lu %lu\n", 0, 42);
	printf("(printf)%llu %llu\n", 0, 42);
	ft_printf("(ft_pri)%llu %llu\n", 0, 42);
	printf("(printf)%hu %hu\n", 0, 42);
	ft_printf("(ft_pri)%hu %hu\n", 0, 42);
	printf("(printf)%hhu %hhu\n", 0, 42);
	ft_printf("(ft_pri)%hhu %hhu\n", 0, 42);	
	printf("(printf)%u\n", UINT_MAX);
	ft_printf("(ft_pri)%u\n", UINT_MAX);
	printf("(printf)%lu\n", ULONG_MAX);
	ft_printf("(ft_pri)%lu\n", ULONG_MAX);
	printf("(printf)%llu\n", ULLONG_MAX);
	ft_printf("(ft_pri)%llu\n", ULLONG_MAX);
	printf("(printf)%hu\n", USHRT_MAX);
	ft_printf("(ft_pri)%hu\n", USHRT_MAX);
	printf("(printf)%hhu\n", UCHAR_MAX);
	ft_printf("(ft_pri)%hhu\n", UCHAR_MAX);

	printf("\n\t\t\tWIDTH TESTS\n");

	printf("~~~~~~~~~d tests:\n");
	printf("(printf)%5d %5d\n", 0, 42);
	ft_printf("(ft_pri)%5d %5d\n", 0, 42);
	printf("(printf)%5ld %5ld\n", 0, 42);
	ft_printf("(ft_pri)%5ld %5ld\n", 0, 42);
	printf("(printf)%1lld %1lld\n", 0, 42);
	ft_printf("(ft_pri)%1lld %1lld\n", 0, 42);
	printf("(printf)%5hd %5hd\n", 0, 42);
	ft_printf("(ft_pri)%5hd %5hd\n", 0, 42);
	printf("(printf)%5hhd %5hhd\n", 0, 42);
	ft_printf("(ft_pri)%5hhd %5hhd\n", 0, 42);
	printf("(printf)%5d %5d\n", -1, -42);
	ft_printf("(ft_pri)%5d %5d\n", -1, -42);
	printf("(printf)%5ld %5ld\n", -1, -42);
	ft_printf("(ft_pri)%5ld %5ld\n", -1, -42);
	printf("(printf)%1lld %1lld\n", -1, -42);
	ft_printf("(ft_pri)%1lld %1lld\n", -1, -42);
	printf("(printf)%5hd %5hd\n", -1, -42);
	ft_printf("(ft_pri)%5hd %5hd\n", -1, -42);
	printf("(printf)%5hhd %5hhd\n", -1, -42);
	ft_printf("(ft_pri)%5hhd %5hhd\n", -1, -42);

	printf("~~~~~~~~~i tests:\n");
	printf("(printf)%5i %5i\n", 0, 42);
	ft_printf("(ft_pri)%5i %5i\n", 0, 42);
	printf("(printf)%5li %5li\n", 0, 42);
	ft_printf("(ft_pri)%5li %5li\n", 0, 42);
	printf("(printf)%1lli %1lli\n", 0, 42);
	ft_printf("(ft_pri)%1lli %1lli\n", 0, 42);
	printf("(printf)%5hi %5hi\n", 0, 42);
	ft_printf("(ft_pri)%5hi %5hi\n", 0, 42);
	printf("(printf)%5hhi %5hhi\n", 0, 42);
	ft_printf("(ft_pri)%5hhi %5hhi\n", 0, 42);
	printf("(printf)%5i %5i\n", -1, -42);
	ft_printf("(ft_pri)%5i %5i\n", -1, -42);
	printf("(printf)%5li %5li\n", -1, -42);
	ft_printf("(ft_pri)%5li %5li\n", -1, -42);
	printf("(printf)%1lli %1lli\n", -1, -42);
	ft_printf("(ft_pri)%1lli %1lli\n", -1, -42);
	printf("(printf)%5hi %5hi\n", -1, -42);
	ft_printf("(ft_pri)%5hi %5hi\n", -1, -42);
	printf("(printf)%5hhi %5hhi\n", -1, -42);
	ft_printf("(ft_pri)%5hhi %5hhi\n", -1, -42);

	printf("~~~~~~~~~o tests:\n");
	printf("(printf)%5o %5o\n", 0, 42);
	ft_printf("(ft_pri)%5o %5o\n", 0, 42);
	printf("(printf)%5lo %5lo\n", 0, 42);
	ft_printf("(ft_pri)%5lo %5lo\n", 0, 42);
	printf("(printf)%1llo %1llo\n", 0, 42);
	ft_printf("(ft_pri)%1llo %1llo\n", 0, 42);
	printf("(printf)%5ho %5ho\n", 0, 42);
	ft_printf("(ft_pri)%5ho %5ho\n", 0, 42);
	printf("(printf)%5hho %5hho\n", 0, 42);
	ft_printf("(ft_pri)%5hho %5hho\n", 0, 42);
	printf("(printf)%5o %5o\n", -1, -42);
	ft_printf("(ft_pri)%5o %5o\n", -1, -42);
	printf("(printf)%5lo %5lo\n", -1, -42);
	ft_printf("(ft_pri)%5lo %5lo\n", -1, -42);
	printf("(printf)%1llo %1llo\n", -1, -42);
	ft_printf("(ft_pri)%1llo %1llo\n", -1, -42);
	printf("(printf)%5ho %5ho\n", -1, -42);
	ft_printf("(ft_pri)%5ho %5ho\n", -1, -42);
	printf("(printf)%5hho %5hho\n", -1, -42);
	ft_printf("(ft_pri)%5hho %5hho\n", -1, -42);

	printf("~~~~~~~~~x tests:\n");
	printf("(printf)%5x %5x\n", 0, 42);
	ft_printf("(ft_pri)%5x %5x\n", 0, 42);
	printf("(printf)%5lx %5lx\n", 0, 42);
	ft_printf("(ft_pri)%5lx %5lx\n", 0, 42);
	printf("(printf)%1llx %1llx\n", 0, 42);
	ft_printf("(ft_pri)%1llx %1llx\n", 0, 42);
	printf("(printf)%5hx %5hx\n", 0, 42);
	ft_printf("(ft_pri)%5hx %5hx\n", 0, 42);
	printf("(printf)%5hhx %5hhx\n", 0, 42);
	ft_printf("(ft_pri)%5hhx %5hhx\n", 0, 42);
	printf("(printf)%5x %5x\n", -1, -42);
	ft_printf("(ft_pri)%5x %5x\n", -1, -42);
	printf("(printf)%5lx %5lx\n", -1, -42);
	ft_printf("(ft_pri)%5lx %5lx\n", -1, -42);
	printf("(printf)%1llx %1llx\n", -1, -42);
	ft_printf("(ft_pri)%1llx %1llx\n", -1, -42);
	printf("(printf)%5hx %5hx\n", -1, -42);
	ft_printf("(ft_pri)%5hx %5hx\n", -1, -42);
	printf("(printf)%5hhx %5hhx\n", -1, -42);
	ft_printf("(ft_pri)%5hhx %5hhx\n", -1, -42);

	printf("~~~~~~~~~X tests:\n");
	printf("(printf)%5X %5X\n", 0, 42);
	ft_printf("(ft_pri)%5X %5X\n", 0, 42);
	printf("(printf)%5lX %5lX\n", 0, 42);
	ft_printf("(ft_pri)%5lX %5lX\n", 0, 42);
	printf("(printf)%1llX %1llX\n", 0, 42);
	ft_printf("(ft_pri)%1llX %1llX\n", 0, 42);
	printf("(printf)%5hX %5hX\n", 0, 42);
	ft_printf("(ft_pri)%5hX %5hX\n", 0, 42);
	printf("(printf)%5hhX %5hhX\n", 0, 42);
	ft_printf("(ft_pri)%5hhX %5hhX\n", 0, 42);
	printf("(printf)%5X %5X\n", -1, -42);
	ft_printf("(ft_pri)%5X %5X\n", -1, -42);
	printf("(printf)%5lX %5lX\n", -1, -42);
	ft_printf("(ft_pri)%5lX %5lX\n", -1, -42);
	printf("(printf)%1llX %1llX\n", -1, -42);
	ft_printf("(ft_pri)%1llX %1llX\n", -1, -42);
	printf("(printf)%5hX %5hX\n", -1, -42);
	ft_printf("(ft_pri)%5hX %5hX\n", -1, -42);
	printf("(printf)%5hhX %5hhX\n", -1, -42);
	ft_printf("(ft_pri)%5hhX %5hhX\n", -1, -42);

	printf("~~~~~~~~~u tests:\n");
	printf("(printf)%5u %5u\n", 0, 42);
	ft_printf("(ft_pri)%5u %5u\n", 0, 42);
	printf("(printf)%5lu %5lu\n", 0, 42);
	ft_printf("(ft_pri)%5lu %5lu\n", 0, 42);
	printf("(printf)%1llu %1llu\n", 0, 42);
	ft_printf("(ft_pri)%1llu %1llu\n", 0, 42);
	printf("(printf)%5hu %5hu\n", 0, 42);
	ft_printf("(ft_pri)%5hu %5hu\n", 0, 42);
	printf("(printf)%5hhu %5hhu\n", 0, 42);
	ft_printf("(ft_pri)%5hhu %5hhu\n", 0, 42);
	printf("(printf)%5u %5u\n", -1, -42);
	ft_printf("(ft_pri)%5u %5u\n", -1, -42);
	printf("(printf)%5lu %5lu\n", -1, -42);
	ft_printf("(ft_pri)%5lu %5lu\n", -1, -42);
	printf("(printf)%1llu %1llu\n", -1, -42);
	ft_printf("(ft_pri)%1llu %1llu\n", -1, -42);
	printf("(printf)%5hu %5hu\n", -1, -42);
	ft_printf("(ft_pri)%5hu %5hu\n", -1, -42);
	printf("(printf)%5hhu %5hhu\n", -1, -42);
	ft_printf("(ft_pri)%5hhu %5hhu\n", -1, -42);


	printf("\n\t\t\tPRECITION TESTS\n");

	printf("~~~~~~~~~d tests:\n");
	printf("(printf)%.5d %.5d\n", 0, 42);
	ft_printf("(ft_pri)%.5d %.5d\n", 0, 42);
	printf("(printf)%.5ld %.5ld\n", 0, 42);
	ft_printf("(ft_pri)%.5ld %.5ld\n", 0, 42);
	printf("(printf)%.5lld %.5lld\n", 0, 42);
	ft_printf("(ft_pri)%.5lld %.5lld\n", 0, 42);
	printf("(printf)%.5hd %.5hd\n", 0, 42);
	ft_printf("(ft_pri)%.5hd %.5hd\n", 0, 42);
	printf("(printf)%.5hhd %.5hhd\n", 0, 42);
	ft_printf("(ft_pri)%.5hhd %.5hhd\n", 0, 42);
	printf("(printf)%.5d %.5d\n", -1, -42);
	ft_printf("(ft_pri)%.5d %.5d\n", -1, -42);
	printf("(printf)%.5ld %.5ld\n", -1, -42);
	ft_printf("(ft_pri)%.5ld %.5ld\n", -1, -42);
	printf("(printf)%.1lld %.1lld\n", -1, -42);
	ft_printf("(ft_pri)%.1lld %.1lld\n", -1, -42);
	printf("(printf)%.5hd %.5hd\n", -1, -42);
	ft_printf("(ft_pri)%.5hd %.5hd\n", -1, -42);
	printf("(printf)%.5hhd %.5hhd\n", -1, -42);
	ft_printf("(ft_pri)%.5hhd %.5hhd\n", -1, -42);

	printf("(printf)%.5d %.5d\n", INT_MIN, INT_MAX);
	ft_printf("(ft_pri)%.5d %.5d\n", INT_MIN, INT_MAX);
	printf("(printf)%.5ld %.5ld\n", LONG_MIN, LONG_MAX);
	ft_printf("(ft_pri)%.5ld %.5ld\n", LONG_MIN, LONG_MAX);
	printf("(printf)%.5lld %.5lld\n", LLONG_MIN, LLONG_MAX);
	ft_printf("(ft_pri)%.5lld %.5lld\n", LLONG_MIN, LLONG_MAX);
	printf("(printf)%.5hd %.5hd\n", SHRT_MIN, SHRT_MAX);
	ft_printf("(ft_pri)%.5hd %.5hd\n", SHRT_MIN, SHRT_MAX);
	printf("(printf)%.5hhd %.5hhd\n", CHAR_MIN, CHAR_MAX);
	ft_printf("(ft_pri)%.5hhd %.5hhd\n", CHAR_MIN, CHAR_MAX);

	printf("~~~~~~~~~i tests:\n");
	printf("(printf)%.5i %.5i\n", 0, 42);
	ft_printf("(ft_pri)%.5i %.5i\n", 0, 42);
	printf("(printf)%.5li %.5li\n", 0, 42);
	ft_printf("(ft_pri)%.5li %.5li\n", 0, 42);
	printf("(printf)%.5lli %.5lli\n", 0, 42);
	ft_printf("(ft_pri)%.5lli %.5lli\n", 0, 42);
	printf("(printf)%.5hi %.5hi\n", 0, 42);
	ft_printf("(ft_pri)%.5hi %.5hi\n", 0, 42);
	printf("(printf)%.5hhi %.5hhi\n", 0, 42);
	ft_printf("(ft_pri)%.5hhi %.5hhi\n", 0, 42);
	printf("(printf)%.5i %.5i\n", -1, -42);
	ft_printf("(ft_pri)%.5i %.5i\n", -1, -42);
	printf("(printf)%.5li %.5li\n", -1, -42);
	ft_printf("(ft_pri)%.5li %.5li\n", -1, -42);
	printf("(printf)%.1lli %.1lli\n", -1, -42);
	ft_printf("(ft_pri)%.1lli %.1lli\n", -1, -42);
	printf("(printf)%.5hi %.5hi\n", -1, -42);
	ft_printf("(ft_pri)%.5hi %.5hi\n", -1, -42);
	printf("(printf)%.5hhi %.5hhi\n", -1, -42);
	ft_printf("(ft_pri)%.5hhi %.5hhi\n", -1, -42);

	printf("(printf)%.5i %.5i\n", INT_MIN, INT_MAX);
	ft_printf("(ft_pri)%.5i %.5i\n", INT_MIN, INT_MAX);
	printf("(printf)%.5li %.5li\n", LONG_MIN, LONG_MAX);
	ft_printf("(ft_pri)%.5li %.5li\n", LONG_MIN, LONG_MAX);
	printf("(printf)%.5lli %.5lli\n", LLONG_MIN, LLONG_MAX);
	ft_printf("(ft_pri)%.5lli %.5lli\n", LLONG_MIN, LLONG_MAX);
	printf("(printf)%.5hi %.5hi\n", SHRT_MIN, SHRT_MAX);
	ft_printf("(ft_pri)%.5hi %.5hi\n", SHRT_MIN, SHRT_MAX);
	printf("(printf)%.5hhi %.5hhi\n", CHAR_MIN, CHAR_MAX);
	ft_printf("(ft_pri)%.5hhi %.5hhi\n", CHAR_MIN, CHAR_MAX);

	ft_printf("~~r spec %r\n", "\r\t\n");
	printf("~~~~~~~~~o tests:\n");
	printf("(printf)%.5o %.5o\n", 0, 42);
	ft_printf("(ft_pri)%.5o %.5o\n", 0, 42);
	printf("(printf)%.5lo %.5lo\n", 0, 42);
	ft_printf("(ft_pri)%.5lo %.5lo\n", 0, 42);
	printf("(printf)%.5llo %.5llo\n", 0, 42);
	ft_printf("(ft_pri)%.5llo %.5llo\n", 0, 42);
	printf("(printf)%.5ho %.5ho\n", 0, 42);
	ft_printf("(ft_pri)%.5ho %.5ho\n", 0, 42);
	printf("(printf)%.5hho %.5hho\n", 0, 42);
	ft_printf("(ft_pri)%.5hho %.5hho\n", 0, 42);
	printf("(printf)%.5o %.5o\n", -1, -42);
	ft_printf("(ft_pri)%.5o %.5o\n", -1, -42);
	printf("(printf)%.5lo %.5lo\n", -1, -42);
	ft_printf("(ft_pri)%.5lo %.5lo\n", -1, -42);
	printf("(printf)%.1llo %.1llo\n", -1, -42);
	ft_printf("(ft_pri)%.1llo %.1llo\n", -1, -42);
	printf("(printf)%.5ho %.5ho\n", -1, -42);
	ft_printf("(ft_pri)%.5ho %.5ho\n", -1, -42);
	printf("(printf)%.5hho %.5hho\n", -1, -42);
	ft_printf("(ft_pri)%.5hho %.5hho\n", -1, -42);
	printf("(printf)%.5o\n", UINT_MAX);
	ft_printf("(ft_pri)%.5o\n", UINT_MAX);
	printf("(printf)%.5lo\n", ULONG_MAX);
	ft_printf("(ft_pri)%.5lo\n", ULONG_MAX);
	printf("(printf)%.5llo\n", ULLONG_MAX);
	ft_printf("(ft_pri)%.5llo\n", ULLONG_MAX);
	printf("(printf)%.5ho\n", USHRT_MAX);
	ft_printf("(ft_pri)%.5ho\n", USHRT_MAX);
	printf("(printf)%.5hho\n", UCHAR_MAX);
	ft_printf("(ft_pri)%.5hho\n", UCHAR_MAX);

	printf("~~~~~~~~~x tests:\n");
	printf("(printf)%.5x %.5x\n", 0, 42);
	ft_printf("(ft_pri)%.5x %.5x\n", 0, 42);
	printf("(printf)%.5lx %.5lx\n", 0, 42);
	ft_printf("(ft_pri)%.5lx %.5lx\n", 0, 42);
	printf("(printf)%.5llx %.5llx\n", 0, 42);
	ft_printf("(ft_pri)%.5llx %.5llx\n", 0, 42);
	printf("(printf)%.5hx %.5hx\n", 0, 42);
	ft_printf("(ft_pri)%.5hx %.5hx\n", 0, 42);
	printf("(printf)%.5hhx %.5hhx\n", 0, 42);
	ft_printf("(ft_pri)%.5hhx %.5hhx\n", 0, 42);
	printf("(printf)%.5x %.5x\n", -1, -42);
	ft_printf("(ft_pri)%.5x %.5x\n", -1, -42);
	printf("(printf)%.5lx %.5lx\n", -1, -42);
	ft_printf("(ft_pri)%.5lx %.5lx\n", -1, -42);
	printf("(printf)%.1llx %.1llx\n", -1, -42);
	ft_printf("(ft_pri)%.1llx %.1llx\n", -1, -42);
	printf("(printf)%.5hx %.5hx\n", -1, -42);
	ft_printf("(ft_pri)%.5hx %.5hx\n", -1, -42);
	printf("(printf)%.5hhx %.5hhx\n", -1, -42);
	ft_printf("(ft_pri)%.5hhx %.5hhx\n", -1, -42);
	printf("(printf)%.5x\n", UINT_MAX);
	ft_printf("(ft_pri)%.5x\n", UINT_MAX);
	printf("(printf)%.5lx\n", ULONG_MAX);
	ft_printf("(ft_pri)%.5lx\n", ULONG_MAX);
	printf("(printf)%.5llx\n", ULLONG_MAX);
	ft_printf("(ft_pri)%.5llx\n", ULLONG_MAX);
	printf("(printf)%.5hx\n", USHRT_MAX);
	ft_printf("(ft_pri)%.5hx\n", USHRT_MAX);
	printf("(printf)%.5hhx\n", UCHAR_MAX);
	ft_printf("(ft_pri)%.5hhx\n", UCHAR_MAX);

	printf("~~~~~~~~~X tests:\n");
	printf("(printf)%.5X %.5X\n", 0, 42);
	ft_printf("(ft_pri)%.5X %.5X\n", 0, 42);
	printf("(printf)%.5lX %.5lX\n", 0, 42);
	ft_printf("(ft_pri)%.5lX %.5lX\n", 0, 42);
	printf("(printf)%.5llX %.5llX\n", 0, 42);
	ft_printf("(ft_pri)%.5llX %.5llX\n", 0, 42);
	printf("(printf)%.5hX %.5hX\n", 0, 42);
	ft_printf("(ft_pri)%.5hX %.5hX\n", 0, 42);
	printf("(printf)%.5hhX %.5hhX\n", 0, 42);
	ft_printf("(ft_pri)%.5hhX %.5hhX\n", 0, 42);
	printf("(printf)%.5X %.5X\n", -1, -42);
	ft_printf("(ft_pri)%.5X %.5X\n", -1, -42);
	printf("(printf)%.5lX %.5lX\n", -1, -42);
	ft_printf("(ft_pri)%.5lX %.5lX\n", -1, -42);
	printf("(printf)%.1llX %.1llX\n", -1, -42);
	ft_printf("(ft_pri)%.1llX %.1llX\n", -1, -42);
	printf("(printf)%.5hX %.5hX\n", -1, -42);
	ft_printf("(ft_pri)%.5hX %.5hX\n", -1, -42);
	printf("(printf)%.5hhX %.5hhX\n", -1, -42);
	ft_printf("(ft_pri)%.5hhX %.5hhX\n", -1, -42);
	printf("(printf)%.5X\n", UINT_MAX);
	ft_printf("(ft_pri)%.5X\n", UINT_MAX);
	printf("(printf)%.5lX\n", ULONG_MAX);
	ft_printf("(ft_pri)%.5lX\n", ULONG_MAX);
	printf("(printf)%.5llX\n", ULLONG_MAX);
	ft_printf("(ft_pri)%.5llX\n", ULLONG_MAX);
	printf("(printf)%.5hX\n", USHRT_MAX);
	ft_printf("(ft_pri)%.5hX\n", USHRT_MAX);
	printf("(printf)%.5hhX\n", UCHAR_MAX);
	ft_printf("(ft_pri)%.5hhX\n", UCHAR_MAX);

	printf("~~~~~~~~~u tests:\n");
	printf("(printf)%.5u %.5u\n", 0, 42);
	ft_printf("(ft_pri)%.5u %.5u\n", 0, 42);
	printf("(printf)%.5lu %.5lu\n", 0, 42);
	ft_printf("(ft_pri)%.5lu %.5lu\n", 0, 42);
	printf("(printf)%.5llu %.5llu\n", 0, 42);
	ft_printf("(ft_pri)%.5llu %.5llu\n", 0, 42);
	printf("(printf)%.5hu %.5hu\n", 0, 42);
	ft_printf("(ft_pri)%.5hu %.5hu\n", 0, 42);
	printf("(printf)%.5hhu %.5hhu\n", 0, 42);
	ft_printf("(ft_pri)%.5hhu %.5hhu\n", 0, 42);
	printf("(printf)%.5u %.5u\n", -1, -42);
	ft_printf("(ft_pri)%.5u %.5u\n", -1, -42);
	printf("(printf)%.5lu %.5lu\n", -1, -42);
	ft_printf("(ft_pri)%.5lu %.5lu\n", -1, -42);
	printf("(printf)%.1llu %.1llu\n", -1, -42);
	ft_printf("(ft_pri)%.1llu %.1llu\n", -1, -42);
	printf("(printf)%.5hu %.5hu\n", -1, -42);
	ft_printf("(ft_pri)%.5hu %.5hu\n", -1, -42);
	printf("(printf)%.5hhu %.5hhu\n", -1, -42);
	ft_printf("(ft_pri)%.5hhu %.5hhu\n", -1, -42);
	printf("(printf)%.5u\n", UINT_MAX);
	ft_printf("(ft_pri)%.5u\n", UINT_MAX);
	printf("(printf)%.5lu\n", ULONG_MAX);
	ft_printf("(ft_pri)%.5lu\n", ULONG_MAX);
	printf("(printf)%.5llu\n", ULLONG_MAX);
	ft_printf("(ft_pri)%.5llu\n", ULLONG_MAX);
	printf("(printf)%.5hu\n", USHRT_MAX);
	ft_printf("(ft_pri)%.5hu\n", USHRT_MAX);
	printf("(printf)%.5hhu\n", UCHAR_MAX);
	ft_printf("(ft_pri)%.5hhu\n", UCHAR_MAX);

	printf("(printf)%.d\n", 0);
	ft_printf("(ft_pri)%.d\n", 0);
	printf("(printf)%.0d\n", 0);
	ft_printf("(ft_pri)%.0d\n", 0);
	printf("(printf)%.i\n", 0);
	ft_printf("(ft_pri)%.i\n", 0);
	printf("(printf)%.0i\n", 0);
	ft_printf("(ft_pri)%.0i\n", 0);
	printf("(printf)%.u\n", 0);
	ft_printf("(ft_pri)%.u\n", 0);
	printf("(printf)%.0u\n", 0);
	ft_printf("(ft_pri)%.0u\n", 0);
	printf("(printf)%.x\n", 0);
	ft_printf("(ft_pri)%.x\n", 0);
	printf("(printf)%.0x\n", 0);
	ft_printf("(ft_pri)%.0x\n", 0);
	printf("(printf)%.X\n", 0);
	ft_printf("(ft_pri)%.X\n", 0);
	printf("(printf)%.0X\n", 0);
	ft_printf("(ft_pri)%.0X\n", 0);
	printf("(printf)%.o\n", 0);
	ft_printf("(ft_pri)%.o\n", 0);
	printf("(printf)%.0o\n", 0);
	ft_printf("(ft_pri)%.0o\n", 0);

	printf("\n\t\t\tPRECITION + WIDTH TESTS\n");

	printf("(printf)%6.5d %9.5d\n", 0, 42);
	ft_printf("(ft_pri)%6.5d %9.5d\n", 0, 42);
	printf("(printf)%6.5i %9.5i\n", -1, -42);
	ft_printf("(ft_pri)%6.5i %9.5i\n", -1, -42);
	printf("(printf)%6.5u %9.5u\n", 0, 42);
	ft_printf("(ft_pri)%6.5u %9.5u\n", 0, 42);
	printf("(printf)%6.5o %9.5o\n", 0, 42);
	ft_printf("(ft_pri)%6.5o %9.5o\n", 0, 42);
	printf("(printf)%6.5x %9.5x\n", 0, 42);
	ft_printf("(ft_pri)%6.5x %9.5x\n", 0, 42);
	printf("(printf)%6.5X %9.5X\n", 0, 42);
	ft_printf("(ft_pri)%6.5X %9.5X\n", 0, 42);
	printf("(printf)%3.5d %3.5d\n", 0, 1024);
	ft_printf("(ft_pri)%3.5d %3.5d\n", 0, 1024);
	printf("(printf)%3.5i %3.5i\n", -1, -1024);
	ft_printf("(ft_pri)%3.5i %3.5i\n", -1, -1024);
	printf("(printf)%3.5u %3.5u\n", 0, 1024);
	ft_printf("(ft_pri)%3.5u %3.5u\n", 0, 1024);
	printf("(printf)%3.5o %3.5o\n", 0, 1024);
	ft_printf("(ft_pri)%3.5o %3.5o\n", 0, 1024);
	printf("(printf)%3.5x %3.5x\n", 0, 1024);
	ft_printf("(ft_pri)%3.5x %3.5x\n", 0, 1024);
	printf("(printf)%3.5X %3.5X\n", 0, 1024);
	ft_printf("(ft_pri)%3.5X %3.5X\n", 0, 1024);

	printf("This is a simple test.\n");
	ft_printf("This is a simple test.\n");
	printf("This is a simple test.\nSecond sentence.\n");
	ft_printf("This is a simple test.\nSecond sentence.\n");
	printf("%s333\n", "222");
	ft_printf("%s333\n", "222");
	printf("111%s333\n", "222");
	ft_printf("111%s333\n", "222");
	printf("111%s", "222\n");
	ft_printf("111%s", "222\n");
	printf("{%s}\n", 0);
	ft_printf("{%s}\n", 0);
	printf("{%s}\n", "");
	ft_printf("{%s}\n", "");
	printf("111%s333%s555\n", "222", "444");
	ft_printf("111%s333%s555\n", "222", "444");
	printf("111%s333%s555%saaa%sccc\n", "222", "444", "666", "bbb");
	ft_printf("111%s333%s555%saaa%sccc\n", "222", "444", "666", "bbb");
	printf("%s%s%s%s%s", "1", "2", "3", "4", "5\n");
	ft_printf("%s%s%s%s%s", "1", "2", "3", "4", "5\n");

	printf("%d\n", 42);
	ft_printf("%d\n", 42);
	printf("%d\n", -42);
	ft_printf("%d\n", -42);
	printf("before %d after\n", 42);
	ft_printf("before %d after\n", 42);
	printf("%d%d%d%d%d\n", 1, -2, 3, -4, 5);
	ft_printf("%d%d%d%d%d\n", 1, -2, 3, -4, 5);
	printf("a%db%dc%dd\n", 1, -2, 3);
	ft_printf("a%db%dc%dd\n", 1, -2, 3);
	printf("%d\n", INT_MAX);
	ft_printf("%d\n", INT_MAX);
	printf("%d\n", INT_MIN);
	ft_printf("%d\n", INT_MIN);

	unsigned long l;
	char *str;
	printf("%p\n", &i);
	ft_printf("%p\n", &i);
	printf("%p\n", &l);
	ft_printf("%p\n", &l);
	printf("%p\n", &str);
	ft_printf("%p\n", &str);
	printf("%p\n", &strlen);
	ft_printf("%p\n", &strlen);
	printf("%p\n", 0);
	ft_printf("%p\n", 0);

	printf("%%\n");
	ft_printf("%%\n");
	printf("aa%%bb\n");
	ft_printf("aa%%bb\n");
	printf("%%%%%%%%%%\n");
	ft_printf("%%%%%%%%%%\n");
	printf(".%%.%%.%%.%%.%%.%%.%%.%%.\n");
	ft_printf(".%%.%%.%%.%%.%%.%%.%%.%%.\n");
	printf("%\n");
	ft_printf("%\n");
	printf("% Zoooo\n");
	ft_printf("% Zoooo\n");
	printf("{%}\n");
	ft_printf("{%}\n");
	printf("{% %}\n");
	ft_printf("{% %}\n");

	printf("s: %s, p: %p, d:%d\n", "a string", &passed_tests, 42);
	ft_printf("s: %s, p: %p, d:%d\n", "a string", &passed_tests, 42);
	printf("%s%p%d%d%p%s%p%p%s\n", "a", &free, 1, 2, &malloc, "b", &free, &malloc, "c");
	ft_printf("%s%p%d%d%p%s%p%p%s\n", "a", &free, 1, 2, &malloc, "b", &free, &malloc, "c");

	printf("%i%i%i%i%i\n", 1, -2, 3, -4, 5);
	ft_printf("%i%i%i%i%i\n", 1, -2, 3, -4, 5);
	printf("a%ib%ic%id\n", 1, -2, 3);
	ft_printf("a%ib%ic%id\n", 1, -2, 3);

	printf("a%ob%oc%od\n", 0, 55555, 100000);
	ft_printf("a%ob%oc%od\n", 0, 55555, 100000);

	printf("a%ub%uc%ud\n", 0, 55555, 100000);
	ft_printf("a%ub%uc%ud\n", 0, 55555, 100000);
	printf("%u\n", UINT_MAX);
	ft_printf("%u\n", UINT_MAX);

	printf("a%xb%xc%xd\n", 0, 55555, 100000);
	ft_printf("a%xb%xc%xd\n", 0, 55555, 100000);
	printf("%x, %x\n", 0, UINT_MAX);
	ft_printf("%x, %x\n", 0, UINT_MAX);
	printf("a%Xb%Xc%Xd\n", 0, 55555, 100000);
	ft_printf("a%Xb%Xc%Xd\n", 0, 55555, 100000);
	printf("%X, %X\n", 0, UINT_MAX);
	ft_printf("%X, %X\n", 0, UINT_MAX);

	printf("%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c \
			%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c\
			%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c\n",
			' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-',
			'.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';',
			'<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
			'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
			'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e',
			'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
			't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}');
	ft_printf("%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c \
				%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c\
				%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c\n",
				' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-',
				'.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';',
				'<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
				'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
				'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e',
				'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
				't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}');
	printf("%c\n", 0);
	ft_printf("%c\n", 0);
	printf("{%10d}\n", 42);
	ft_printf("{%10d}\n", 42);
	printf("{%30d}\n", 10000);
	ft_printf("{%30d}\n", 10000);
	printf("{%4d}\n", 10000);
	ft_printf("{%4d}\n", 10000);
	printf("{%10d}\n", -42);
	ft_printf("{%10d}\n", -42);
	printf("{%3c}\n", 0);
	ft_printf("{%3c}\n", 0);
	printf("{%5p}\n", 0);
	ft_printf("{%5p}\n", 0);
	printf("{%-15p}\n", 0);
	ft_printf("{%-15p}\n", 0);
	printf("{%-13p}\n", &strlen);
	ft_printf("{%-13p}\n", &strlen);
	printf("{%-12p}\n", &strlen);
	ft_printf("{%-12p}\n", &strlen);

	i = printf("%D\n", 0L);
	j = ft_printf("%D\n", 0L);
	//assert(i==j);
	i = printf("%D\n", 1L);
	j = ft_printf("%D\n", 1L);
	//assert(i==j);
	i = printf("%D\n", -1L);
	j = ft_printf("%D\n", -1L);
	//assert(i==j);
	i = printf("%D\n", 42L);
	j = ft_printf("%D\n", 42L);
	//assert(i==j);
	i = printf("%D\n", LONG_MAX);
	j = ft_printf("%D\n", LONG_MAX);
	//assert(i==j);
	i = printf("%D\n", LONG_MIN);
	j = ft_printf("%D\n", LONG_MIN);
	//assert(i==j);
	i = printf("Coucou les %D!\n", 42);
	j = ft_printf("Coucou les %D!\n", 42);
	//assert(i==j);
	i = printf("{%10R}\n");
	j = ft_printf("{%10R}\n");
	//assert(i==j);
	i = printf("{%# 12.10R}\n");
	j = ft_printf("{%# 12.10R}\n");
	//assert(i==j);
	i = printf("{% 0-#+12.10R}\n");
	j = ft_printf("{% 0-#+12.10R}\n");
	//assert(i==j);
	i = printf("{% 0#12.10R}\n");
	j = ft_printf("{% 0#12.10R}\n");
	//assert(i==j);

	i = printf("%lp\n", 42);
	j = ft_printf("%lp\n", 42);
	assert(i==j);
	i = printf("{%-10d}\n", 42);
	j = ft_printf("{%-10d}\n", 42);
	assert(i==j);
	i = printf("{%-4d}\n", 10000);
	j = ft_printf("{%-4d}\n", 10000);
	assert(i==j);
	i = printf("{%-30d}\n", 10000);
	j = ft_printf("{%-30d}\n", 10000);
	assert(i==j);
	i = printf("{%010d}\n", 42);
	j = ft_printf("{%010d}\n", 42);
	assert(i==j);
	i = printf("{%010d}\n", -42);
	j = ft_printf("{%010d}\n", -42);
	assert(i==j);
	i = printf("{%04d}\n", 10000);
	j = ft_printf("{%04d}\n", 10000);
	assert(i==j);
	i = printf("{%030d}\n", 10000);
	j = ft_printf("{%030d}\n", 10000);
	assert(i==j);
	i = printf("{%030x}\n", 0xFFFF);
	j = ft_printf("{%030x}\n", 0xFFFF);
	assert(i==j);
	i = printf("{%030X}\n", 0xFFFF);
	j = ft_printf("{%030X}\n", 0xFFFF);
	assert(i==j);
	i = printf("{%03c}\n", 0);
	j = ft_printf("{%03c}\n", 0);
	assert(i==j);
	i = printf("{%05s}\n", "abc");
	j = ft_printf("{%05s}\n", "abc");
	assert(i==j);
	i = printf("{%05p}\n", 0);
	j = ft_printf("{%05p}\n", 0);
	assert(i==j);
	i = printf("{%05p}\n", &passed_tests);
	j = ft_printf("{%05p}\n", &passed_tests);
	assert(i==j);
	i = printf("{%-15R}\n", 123);
	j = ft_printf("{%-15R}\n", 123);
	assert(i==j);
	i = printf("%#o\n", 42);
	j = ft_printf("%#o\n", 42);
	assert(i==j);
	i = printf("%#o\n", 0);
	j = ft_printf("%#o\n", 0);
	assert(i==j);
	i = printf("%#o\n", INT_MAX);
	j = ft_printf("%#o\n", INT_MAX);
	assert(i==j);
	i = printf("%#O\n", 1);
	j = ft_printf("%#O\n", 1);
	assert(i==j);
	i = printf("%#x\n", 42);
	j = ft_printf("%#x\n", 42);
	assert(i==j);
	i = printf("%#x\n", 0);
	j = ft_printf("%#x\n", 0);
	assert(i==j);
	i = printf("%#x\n", INT_MAX);
	j = ft_printf("%#x\n", INT_MAX);
	assert(i==j);
	i = printf("%#X\n", 42);
	j = ft_printf("%#X\n", 42);
	assert(i==j);
	i = printf("%#X\n", 0);
	j = ft_printf("%#X\n", 0);
	assert(i==j);
	i = printf("%#X\n", INT_MAX);
	j = ft_printf("%#X\n", INT_MAX);
	assert(i==j);
	i = printf("%#c\n", 0);
	j = ft_printf("%#c\n", 0);
	assert(i==j);

	i = printf("%+d\n", 42);
	j = ft_printf("%+d\n", 42);
	assert(i==j);
	i = printf("%+d\n", -42);
	j = ft_printf("%+d\n", -42);
	assert(i==j);
	i = printf("%+i\n", 42);
	j = ft_printf("%+i\n", 42);
	assert(i==j);
	i = printf("%+i\n", -42);
	j = ft_printf("%+i\n", -42);
	assert(i==j);
	i = printf("%+c\n", 0);
	j = ft_printf("%+c\n", 0);
	assert(i==j);
	i = printf("%+o\n", 0);
	j = ft_printf("%+o\n", 0);
	assert(i==j);
	i = printf("%+o\n", 42);
	j = ft_printf("%+o\n", 42);
	assert(i==j);
	i = printf("%+O\n", 0);
	j = ft_printf("%+O\n", 0);
	assert(i==j);
	i = printf("%+O\n", 42);
	j = ft_printf("%+O\n", 42);
	assert(i==j);
	i = printf("[%+s]\n", 0);
	j = ft_printf("[%+s]\n", 0);
	assert(i==j);
	i = printf("[%+s]\n", "(null)");
	j = ft_printf("[%+s]\n", "(null)");
	assert(i==j);
	i = printf("%+O\n", 1);
	j = ft_printf("%+O\n", 1);
	assert(i==j);

	i = printf("% d\n", 9999);
	j = ft_printf("% d\n", 9999);
	assert(i==j);
	i = printf("% d\n", -9999);
	j = ft_printf("% d\n", -9999);
	assert(i==j);
	i = printf("% i\n", 9999);
	j = ft_printf("% i\n", 9999);
	assert(i==j);
	i = printf("% i\n", -9999);
	j = ft_printf("% i\n", -9999);
	assert(i==j);
	i = printf("% u\n", 9999);
	j = ft_printf("% u\n", 9999);
	assert(i==j);
	i = printf("{% c}\n", 0);
	j = ft_printf("{% c}\n", 0);
	assert(i==j);
	i = printf("{% c}\n", 'a');
	j = ft_printf("{% c}\n", 'a');
	assert(i==j);
	i = printf("{% s}\n", NULL);
	j = ft_printf("{% s}\n", NULL);
	assert(i==j);
	i = printf("{% s}\n", "(null)");
	j = ft_printf("{% s}\n", "(null)");
	assert(i==j);
	i = printf("{% s}\n", "");
	j = ft_printf("{% s}\n", "");
	assert(i==j);

	i = printf("{% +d}\n", 42);
	j = ft_printf("{% +d}\n", 42);
	assert(i==j);
	i = printf("{%+ d}\n", 42);
	j = ft_printf("{%+ d}\n", 42);
	assert(i==j);
	i = printf("{%+03d}\n", 0);
	j = ft_printf("{%+03d}\n", 0);
	assert(i==j);
	i = printf("{% 03d}\n", 0);
	j = ft_printf("{% 03d}\n", 0);
	assert(i==j);
	i = printf("{%0-3d}\n", 0);
	j = ft_printf("{%0-3d}\n", 0);
	assert(i==j);
	i = printf("{%+03d}\n", 12);
	j = ft_printf("{%+03d}\n", 12);
	assert(i==j);
	i = printf("{%+03d}\n", 123456);
	j = ft_printf("{%+03d}\n", 123456);
	assert(i==j);
	i = printf("{%03.2d}\n", 0);
	j = ft_printf("{%03.2d}\n", 0);
	assert(i==j);
	i = printf("%#.O\n", 0);
	j = ft_printf("%#.O\n", 0);
	assert(i==j);

		i = printf("%.4d\n", 42);
	j = ft_printf("%.4d\n", 42);
	assert(i==j);
	i = printf("%.4d\n", 424242);
	j = ft_printf("%.4d\n", 424242);
	assert(i==j);
	i = printf("%.4d\n", -424242);
	j = ft_printf("%.4d\n", -424242);
	assert(i==j);
	i = printf("%15.4d\n", 42);
	j = ft_printf("%15.4d\n", 42);
	assert(i==j);
	i = printf("%15.4d\n", 424242);
	j = ft_printf("%15.4d\n", 424242);
	assert(i==j);
	i = printf("%8.4d\n", 424242424);
	j = ft_printf("%8.4d\n", 424242424);
	assert(i==j);
	i = printf("%15.4d\n", -42);
	j = ft_printf("%15.4d\n", -42);
	assert(i==j);
	i = printf("%15.4d\n", -424242);
	j = ft_printf("%15.4d\n", -424242);
	assert(i==j);
	i = printf("%8.4d\n", -424242424);
	j = ft_printf("%8.4d\n", -424242424);
	assert(i==j);
	i = printf("%4.15d\n", 42);
	j = ft_printf("%4.15d\n", 42);
	assert(i==j);
	i = printf("%4.15d\n", 424242);
	j = ft_printf("%4.15d\n", 424242);
	assert(i==j);
	i = printf("%4.8d\n", 424242424);
	j = ft_printf("%4.8d\n", 424242424);
	assert(i==j);
	i = printf("%4.15d\n", -42);
	j = ft_printf("%4.15d\n", -42);
	assert(i==j);
	i = printf("%4.15d\n", -424242);
	j = ft_printf("%4.15d\n", -424242);
	assert(i==j);
	i = printf("%4.8d\n", -424242424);
	j = ft_printf("%4.8d\n", -424242424);
	assert(i==j);
	i = printf("%.d, %.0d\n", 0, 0);
	j = ft_printf("%.d, %.0d\n", 0, 0);
	assert(i==j);
	i = printf("%.10d\n", -42);
	j = ft_printf("%.10d\n", -42);
	assert(i==j);
	i = printf("%.4i\n", 42);
	j = ft_printf("%.4i\n", 42);
	assert(i==j);
	i = printf("%15.4i\n", 42);
	j = ft_printf("%15.4i\n", 42);
	assert(i==j);
	i = printf("%4.15i\n", 42);
	j = ft_printf("%4.15i\n", 42);
	assert(i==j);
	i = printf("%.i, %.0i\n", 0, 0);
	j = ft_printf("%.i, %.0i\n", 0, 0);
	assert(i==j);
	i = printf("%.4u\n", 42);
	j = ft_printf("%.4u\n", 42);
	assert(i==j);
	i = printf("%.4u\n", 424242);
	j = ft_printf("%.4u\n", 424242);
	assert(i==j);
	i = printf("%15.4u\n", 42);
	j = ft_printf("%15.4u\n", 42);
	assert(i==j);
	i = printf("%15.4u\n", 424242);
	j = ft_printf("%15.4u\n", 424242);
	assert(i==j);
	i = printf("%8.4u\n", 424242424);
	j = ft_printf("%8.4u\n", 424242424);
	assert(i==j);
	i = printf("%4.15u\n", 42);
	j = ft_printf("%4.15u\n", 42);
	assert(i==j);
	i = printf("%4.15u\n", 424242);
	j = ft_printf("%4.15u\n", 424242);
	assert(i==j);
	i = printf("%4.8u\n", 424242424);
	j = ft_printf("%4.8u\n", 424242424);
	assert(i==j);
	i = printf("%.u, %.0u\n", 0, 0);
	j = ft_printf("%.u, %.0u\n", 0, 0);
	assert(i==j);

	i = printf("%.4o\n", 42);
	j = ft_printf("%.4o\n", 42);
	assert(i==j);
	i = printf("%.4o\n", 424242);
	j = ft_printf("%.4o\n", 424242);
	assert(i==j);
	i = printf("%15.4o\n", 42);
	j = ft_printf("%15.4o\n", 42);
	assert(i==j);
	i = printf("%15.4o\n", 424242);
	j = ft_printf("%15.4o\n", 424242);
	assert(i==j);
	i = printf("%8.4o\n", 424242424);
	j = ft_printf("%8.4o\n", 424242424);
	assert(i==j);
	i = printf("%4.15o\n", 42);
	j = ft_printf("%4.15o\n", 42);
	assert(i==j);
	i = printf("%4.15o\n", 424242);
	j = ft_printf("%4.15o\n", 424242);
	assert(i==j);
	i = printf("%4.8o\n", 424242424);
	j = ft_printf("%4.8o\n", 424242424);
	assert(i==j);
	i = printf("%.o, %.0o\n", 0, 0);
	j = ft_printf("%.o, %.0o\n", 0, 0);
	assert(i==j);

	i = printf("%.4x\n", 42);
	j = ft_printf("%.4x\n", 42);
	assert(i==j);
	i = printf("%15.4x\n", 42);
	j = ft_printf("%15.4x\n", 42);
	assert(i==j);
	i = printf("%15.4x\n", 424242);
	j = ft_printf("%15.4x\n", 424242);
	assert(i==j);
	i = printf("%8.4x\n", 424242424);
	j = ft_printf("%8.4x\n", 424242424);
	assert(i==j);
	i = printf("%4.15x\n", 42);
	j = ft_printf("%4.15x\n", 42);
	assert(i==j);
	i = printf("%4.15x\n", 424242);
	j = ft_printf("%4.15x\n", 424242);
	assert(i==j);
	i = printf("%4.8x\n", 424242424);
	j = ft_printf("%4.8x\n", 424242424);
	assert(i==j);
	i = printf("%.x, %.0x\n", 0, 0);
	j = ft_printf("%.x, %.0x\n", 0, 0);
	assert(i==j);

	i = printf("%.4X\n", 42);
	j = ft_printf("%.4X\n", 42);
	assert(i==j);
	i = printf("%.4X\n", 424242);
	j = ft_printf("%.4X\n", 424242);
	assert(i==j);
	i = printf("%15.4X\n", 42);
	j = ft_printf("%15.4X\n", 42);
	assert(i==j);
	i = printf("%15.4X\n", 424242);
	j = ft_printf("%15.4X\n", 424242);
	assert(i==j);
	i = printf("%8.4X\n", 424242424);
	j = ft_printf("%8.4X\n", 424242424);
	assert(i==j);
	i = printf("%4.15X\n", 42);
	j = ft_printf("%4.15X\n", 42);
	assert(i==j);
	i = printf("%4.15X\n", 424242);
	j = ft_printf("%4.15X\n", 424242);
	assert(i==j);
	i = printf("%4.8X\n", 424242424);
	j = ft_printf("%4.8X\n", 424242424);
	assert(i==j);
	i = printf("%.X, %.0X\n", 0, 0);
	j = ft_printf("%.X, %.0X\n", 0, 0);
	assert(i==j);

	i = printf("%.4s\n", "42");
	j = ft_printf("%.4s\n", "42");
	assert(i==j);
	i = printf("%.4s\n", "42 is the answer");
	j = ft_printf("%.4s\n", "42 is the answer");
	assert(i==j);
	i = printf("%15.4s\n", "42");
	j = ft_printf("%15.4s\n", "42");
	assert(i==j);
	i = printf("%15.4s\n", "I am 42");
	j = ft_printf("%15.4s\n", "I am 42");
	assert(i==j);
	i = printf("%15.4s\n", "42 is the answer");
	j = ft_printf("%15.4s\n", "42 is the answer");
	assert(i==j);
	i = printf("%4.15s\n", "42");
	j = ft_printf("%4.15s\n", "42");
	assert(i==j);
	i = printf("%4.15s\n", "I am 42");
	j = ft_printf("%4.15s\n", "I am 42");
	assert(i==j);
	i = printf("%4.15s\n", "42 is the answer");
	j = ft_printf("%4.15s\n", "42 is the answer");
	assert(i==j);
	i = printf("%4.s\n", "42");
	j = ft_printf("%4.s\n", "42");
	assert(i==j);

	i = printf("%.c\n", 0);
	j = ft_printf("%.c\n", 0);
	assert(i==j);
	i = printf("%.5c\n", 0);
	j = ft_printf("%.5c\n", 0);
	assert(i==j);
	i = printf("%.5c\n", 42);
	j = ft_printf("%.5c\n", 42);
	assert(i==j);

	i = printf("%.0p, %.p\n", 0, 0);
	j = ft_printf("%.0p, %.p\n", 0, 0);
	assert(i==j);
	i = printf("%.5p\n", 0);
	j = ft_printf("%.5p\n", 0);
	assert(i==j);
	i = printf("%9.2p\n", 1234);
	j = ft_printf("%9.2p\n", 1234);
	assert(i==j);
	i = printf("%9.2p\n", 1234567);
	j = ft_printf("%9.2p\n", 1234567);
	assert(i==j);
	i = printf("%2.9p\n", 1234);
	j = ft_printf("%2.9p\n", 1234);
	assert(i==j);
	i = printf("%2.9p\n", 1234567);
	j = ft_printf("%2.9p\n", 1234567);
	assert(i==j);

	i = printf("%.3%\n");
	j = ft_printf("%.3%\n");
	assert(i==j);

	i = printf("%#.o, %#.0o\n", 0, 0);
	j = ft_printf("%#.o, %#.0o\n", 0, 0);
	assert(i==j);
	i = printf("%#.x, %#.0x\n", 0, 0);
	j = ft_printf("%#.x, %#.0x\n", 0, 0);
	assert(i==j);
	i = printf("%.p, %.0p\n", 0, 0);
	j = ft_printf("%.p, %.0p\n", 0, 0);
	assert(i==j);
	i = printf("{%05.c}\n", 0);
	j = ft_printf("{%05.c}\n", 0);
	assert(i==j);
	i = printf("{%05.s}\n", 0);
	j = ft_printf("{%05.s}\n", 0);
	assert(i==j);
	i = printf("{%05.%}\n", 0);
	j = ft_printf("{%05.%}\n", 0);
	assert(i==j);
	i = printf("{%05.R}\n", 0);
	j = ft_printf("{%05.R}\n", 0);
	assert(i==j);
	i = printf("{%#.5x}\n", 1);
	j = ft_printf("{%#.5x}\n", 1);
	assert(i==j);
	i = printf("%#.3o\n", 1);
	j = ft_printf("%#.3o\n", 1);
	assert(i==j);

	i = printf("%hhd - %hhd\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	j = ft_printf("%hhd - %hhd\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	assert(i==j);
	i = printf("%i\n", LLONG_MIN);
	j = ft_printf("%i\n", LLONG_MIN);
	assert(i==j);
	i = printf("%d\n", LLONG_MIN);
	j = ft_printf("%d\n", LLONG_MIN);
	assert(i==j);
	i = printf("% p|%+p\n", 42, 42);
	j = ft_printf("% p|%+p\n", 42, 42);
	assert(i==j);

	i = printf("%u\n", -42);
	j = ft_printf("%u\n", -42);
	assert(i==j);
	i = printf("%u\n", UINT_MAX + 1);
	j = ft_printf("%u\n", UINT_MAX + 1);
	assert(i==j);
	i = printf("%U\n", ULONG_MAX + 1);
	j = ft_printf("%U\n", ULONG_MAX + 1);
	assert(i==j);
	i = printf("%c\n", 200);
	j = ft_printf("%c\n", 200);
	assert(i==j);
	i = printf("% u|%+u\n", 42, 42);
	j = ft_printf("% u|%+u\n", 42, 42);
	assert(i==j);
	i = printf("%hhu / %hhu\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	j = ft_printf("%hhu / %hhu\n", SHRT_MAX - 42,  SHRT_MAX - 4200);
	assert(i==j);

	i = printf("%o, %ho, %hho\n", -42, -42, -42);
	j = ft_printf("%o, %ho, %hho\n", -42, -42, -42);
	assert(i==j);
	i = printf("%o\n", LONG_MAX);
	j = ft_printf("%o\n", LONG_MAX);
	assert(i==j);
	i = printf("%O\n", LONG_MIN);
	j = ft_printf("%O\n", LONG_MIN);
	assert(i==j);
	i = printf("% o|%+o\n", 42, 42);
	j = ft_printf("% o|%+o\n", 42, 42);
	assert(i==j);
	i = printf("%#.o\n", 42);
	j = ft_printf("%#.o\n", 42);
	assert(i==j);
	i = printf("% x|%+x\n", 42, 42);
	j = ft_printf("% x|%+x\n", 42, 42);
	assert(i==j);
	i = printf("% X|%+X\n", 42, 42);
	j = ft_printf("% X|%+X\n", 42, 42);
	assert(i==j);

	i = printf("{%f}{%F}\n", 1.42, 1.42);
	j = ft_printf("{%f}{%F}\n", 1.42, 1.42);
	assert(i==j);
	i = printf("{%f}{%F}\n", -1.42, -1.42);
	j = ft_printf("{%f}{%F}\n", -1.42, -1.42);
	assert(i==j);
	i = printf("{%f}{%F}\n", 1444565444646.6465424242242, 1444565444646.6465424242242);
	j = ft_printf("{%f}{%F}\n", 1444565444646.6465424242242, 1444565444646.6465424242242);
	assert(i==j);
	i = printf("{%f}{%F}\n", -1444565444646.6465424242242454654, -1444565444646.6465424242242454654);
	j = ft_printf("{%f}{%F}\n", -1444565444646.6465424242242454654, -1444565444646.6465424242242454654);
	assert(i==j);
}

int		ft_get_exponent3(char *str)
{
	int	exponent;
	int	sign;

	exponent = 0;
	sign = *str == '0';
	if (sign)
	{
		while (*str && (*str <= '1' || *str >= '9'))
		{
			if (*str != '.')
				exponent++;
			str++;
		}
	}
	else
	{
		while (*str && *str != '.')
		{
			exponent++;
			str++;
		}
	}
	exponent--;
	if (sign)
		exponent *= -1;
	return (exponent);
}

char	*ft_double_to_exp3(long double num, int precition)
{
	char	*fstr;
	int		exponent;
	char *str;
	//int		precition;

	precition = precition >= 0 ? precition : 6;
	if (!(fstr = ft_ftoa(num, 18)))
		return (NULL);
	printf("%.18Lf\n", num);
	exponent = ft_get_exponent3(fstr);
	printf("%d\n", exponent);
	printf("%s\n", fstr);
	free(fstr);
	if (exponent > 0)
		num /= ft_pow(10, exponent);
	if (exponent < 0)
		num *= ft_pow(10, -exponent);
	fstr = ft_ftoa(num, precition);fstr = ft_ftoa(num, precition);
	str = ft_strnew(ft_strlen(fstr) + 4);
	ft_strcat(str, fstr);
	free(fstr);
	fstr = ft_itoa(exponent);
	ft_strcat(str, "e");
	ft_strcat(str, fstr);

	ft_printf("%.2e\n", 12.49);
	printf("%.2e\n", 12.49);
	ft_printf("%.2e\n", 0.0001249);
	printf("%.2e\n", 0.0001249);

	ft_printf("%+-e\n", 12.49);
	printf("%+-e\n", 12.49);
	ft_printf("%+-e\n", 0.0001249);
	printf("%+-e\n", 0.0001249);

	ft_printf("%+-e\n", -12.49);
	printf("%+-e\n", -12.49);
	ft_printf("%+-e\n", -0.0001249);
	printf("%+-e\n", -0.0001249);

	ft_printf("%#e\n", 12.49);
	printf("%#e\n", 12.49);
	ft_printf("% 20e\n", 0.0001249);
	printf("% 20e\n", 0.0001249);

	ft_printf("%#.10e\n", -12.49);
	printf("%#.10e\n", -12.49);
	ft_printf("% 20.10e\n", -0.0001249);
	printf("% 20.10e\n", -0.0001249);

	ft_printf("%#.10e\n", -1.49);
	printf("%#.10e\n", -1.49);
	ft_printf("%.e\n", 1.249);
	printf("%.e\n", 1.249);

	printf("%g\n", 1.239999);
	ft_printf("%g\n", 1.239999);

	printf("%.g\n", 1.239999);
	ft_printf("%.g\n", 1.239999);
	printf("%.2g\n", 123999.9);
	ft_printf("%.2g\n", 123999.9);
	printf("%.4g\n", 121111.9);
	ft_printf("%.4g\n", 121111.9);
	printf("%.9g\n", 1211110000.9);
	ft_printf("%.9g\n", 1211110000.9);
	printf("%.5g\n", 121111.9);
	ft_printf("%.5g\n", 121111.9);
	printf("%20.15g\n", 0.00012);
	ft_printf("%20.15g\n", 0.00012);

	printf("%g\n", 1.2345678);
	ft_printf("%g\n", 1.2345678);

	return (str);
}

int main(void)
{
//	int i, j;
//	i = ft_printf("%20.15f\n", 12345.1234);
//	j = ft_printf("%20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%+20.15f\n", 12345.1234);
//	j = ft_printf("%+20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%-20.15f\n", 12345.1234);
//	j = ft_printf("%-20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%20.15f\n", -12345.1234);
//	j = ft_printf("%20.15f\n", -12345.1234);
//	assert(i == j);
//	i = ft_printf("%20.15f\n", 12345.1234);
//	j = ft_printf("%20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%20.15f\n", 12345.1234);
//	j = ft_printf("%20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%20.15f\n", 12345.1234);
//	j = ft_printf("%20.15f\n", 12345.1234);
//	assert(i == j);
//	i = ft_printf("%20.15f\n", 12345.1234);
//	j = ft_printf("%20.15f\n", 12345.1234);
//	assert(i == j);
//	passed_tests();

//	int x = printf("{%05.c}\n\n", 0);
//	int y = ft_printf("{%05.c}", 0);
int y = ft_printf("% ");
	printf("%d\n", y);
	int x = printf("% ");
	printf("%d ", x);
	//ft_printf("% p|%+p", 42, 42);
	return 0;
}
