OCAMLMAKEFILE = ../OCamlMakefile

SOURCES = Atom.ml First_twenty.ml Molecule.ml Molecules.ml Alkane.ml Alkanes.ml \
		  Reaction.ml Reactions.ml main.ml
RESULT = a.out
THREAD = yes

include $(OCAMLMAKEFILE)
