OCAMLMAKEFILE = ./OCamlMakefile

SOURCES = Block.mli Grid.mli Board.mli Player.mli Cmd.mli Gui.mli Game.mli \
		  Block.ml Grid.ml Board.ml Player.ml Cmd.ml Gui.ml Game.ml
RESULT = rush00
PACKS = graphics
THREAD = yes

include $(OCAMLMAKEFILE)
