# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoApp
  pod 'MapboxNavigation', '~> 0.22.0'

  target 'GeoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
