# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day07' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day07
  pod "ForecastIO"
  pod "RecastAI"
  #pod 'MessageKit'
  pod "MessageKit", '0.13.0'

end
